version: '2'
services:
  postgres:
    image: postgres:9.4
    volumes:
      - "data:/var/lib/postgresql/data"
  web:
    build: .
    image: hacker_registration:development
    command: rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: 'true'
      SECRET_KEY_BASE: de7261ae75f8
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/hacker_registration
    depends_on:
      - postgres
volumes:
  data: {}
